version: 0.2

phases:
  install:
    commands:
      - echo Installing required packages...
      - pip install -r backend/requirements.txt

  pre_build:
    commands:
      - echo Pulling source code...
      - git pull origin main

  build:
    commands:
      - echo Restarting uvicorn service...
      - systemctl --user restart tutora-backend.service


